Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. Wszelkie prawa zastrze¿one.

C:\Users\student>cd ..

C:\Users>cd ..

C:\>cd Python27

C:\Python27>cd Lib

C:\Python27\Lib>cd site-packages

C:\Python27\Lib\site-packages>cd django

C:\Python27\Lib\site-packages\django>cd bin

C:\Python27\Lib\site-packages\django\bin>cd mysite

C:\Python27\Lib\site-packages\django\bin\mysite>"C:\Python27\python.exe" manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  No migrations to apply.

C:\Python27\Lib\site-packages\django\bin\mysite>
C:\Python27\Lib\site-packages\django\bin\mysite>"C:\Python27\python.exe" manage.py makemigrations an
kieta
Migrations for 'ankieta':
  ankieta\migrations\0001_initial.py:
    - Create model Choice
    - Create model Question

C:\Python27\Lib\site-packages\django\bin\mysite>"C:\Python27\python.exe" manage.py sqlmigrate ankiet
a 0001
BEGIN;
--
-- Create model Choice
--
CREATE TABLE "ankieta_choice" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "choice_text" varcha
r(200) NOT NULL, "votes" integer NOT NULL);
--
-- Create model Question
--
CREATE TABLE "ankieta_question" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "question_text" va
rchar(200) NOT NULL, "pub_date" datetime NOT NULL);
COMMIT;

C:\Python27\Lib\site-packages\django\bin\mysite>"C:\Python27\python.exe" manage.py migrate
Operations to perform:
  Apply all migrations: admin, ankieta, auth, contenttypes, sessions
Running migrations:
  Applying ankieta.0001_initial... OK

C:\Python27\Lib\site-packages\django\bin\mysite>"C:\Python27\python.exe" manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
January 17, 2017 - 18:30:25
Django version 1.10.4, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

C:\Python27\Lib\site-packages\django\bin\mysite>^D^D^Q
'¦¦<' is not recognized as an internal or external command,
operable program or batch file.

C:\Python27\Lib\site-packages\django\bin\mysite>
C:\Python27\Lib\site-packages\django\bin\mysite>
C:\Python27\Lib\site-packages\django\bin\mysite>
C:\Python27\Lib\site-packages\django\bin\mysite>
C:\Python27\Lib\site-packages\django\bin\mysite>
C:\Python27\Lib\site-packages\django\bin\mysite>
C:\Python27\Lib\site-packages\django\bin\mysite>
C:\Python27\Lib\site-packages\django\bin\mysite>
C:\Python27\Lib\site-packages\django\bin\mysite>
C:\Python27\Lib\site-packages\django\bin\mysite>
C:\Python27\Lib\site-packages\django\bin\mysite>
C:\Python27\Lib\site-packages\django\bin\mysite>"C:\Python27\python.exe" manage.py createsuperuser
Username: student
Error: That username is already taken.
Username: studentstudent
Email address: student@student.pl
Password:
Password (again):
Superuser created successfully.

C:\Python27\Lib\site-packages\django\bin\mysite>"C:\Python27\python.exe" manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
January 17, 2017 - 18:35:22
Django version 1.10.4, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

C:\Python27\Lib\site-packages\django\bin\mysite>"C:\Python27\python.exe" manage.py shell
Python 2.7.6 (default, Nov 10 2013, 19:24:24) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from ankieta.models import Question, Choice
>>> Question.objects.all()
<QuerySet []>
>>> from django.utils import timezone
>>> q=Question(question_text="Co nowego?",pub_date=timezone.now())
>>> q.save()
>>> q.id
1
>>> q.question_text
'Co nowego?'
>>> q.pub_date
datetime.datetime(2017, 1, 17, 17, 41, 37, 568000, tzinfo=<UTC>)
>>> q.question_text="Co sie stalo?"
>>> q.save()
>>> Question.objects.all
<bound method Manager.all of <django.db.models.manager.Manager object at 0x00000000036B08D0>>
>>> Question.objects.all()
<QuerySet [<Question: Question object>]>
>>> q
<Question: Question object>
>>>
>>>
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from
_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 357, in execute
    translation.activate(saved_locale)
  File "C:\Python27\lib\site-packages\django\utils\translation\__init__.py", line 161, in activate
    return _trans.activate(language)
  File "C:\Python27\lib\site-packages\django\utils\translation\__init__.py", line 57, in __getattr__

    if settings.USE_I18N:
  File "C:\Python27\lib\site-packages\django\conf\__init__.py", line 51, in __getattr__
    def __getattr__(self, name):
KeyboardInterrupt

C:\Python27\Lib\site-packages\django\bin\mysite>"C:\Python27\python.exe" manage.py shell
Python 2.7.6 (default, Nov 10 2013, 19:24:24) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from ankieta.models import Question, Choice
>>> Question.objects.all()
<QuerySet [<Question: Co sie stalo?>]>
>>> Question.objects.filter(id=1)
<QuerySet [<Question: Co sie stalo?>]>
>>> Question.objects.filter(question_text__startwith='Co')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Python27\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 796, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 814, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1227, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1253, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "C:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1187, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1081, in build_lookup
    lhs = self.try_transform(lhs, name, lookups)
  File "C:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1099, in try_transform
    (name, lhs.output_field.__class__.__name__))
FieldError: Unsupported lookup 'startwith' for CharField or join on the field not permitted.
>>> Question.objects.filter(question_text__startswith='Co')
<QuerySet [<Question: Co sie stalo?>]>
>>> from django.utils import timezone
>>> current_year = timezone.now().year
>>> Question.objects.filter(pub_date__year=current_year)
<QuerySet [<Question: Co sie stalo?>]>
>>> Question.objects.get(id=2)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Python27\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 385, in get
    self.model._meta.object_name
DoesNotExist: Question matching query does not exist.
>>>